src/gz base https://ray.ws1608.ggff.net/aarch64_cortex-a53/base
src/gz kmod https://ray.ws1608.ggff.net/aarch64_cortex-a53/kmod
src/gz luci https://ray.ws1608.ggff.net/aarch64_cortex-a53/luci
src/gz packages https://ray.ws1608.ggff.net/aarch64_cortex-a53/packages